export const  ladiesNight = [
  {
    eventName: "DREAM DINNER SHOW WED TO SUN",
    days: "Wed-Sun",
    time: "8 PM - 3 AM",
    venue: "Dream Restaurant",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Dream-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    eventName: "KING PAPA FRIDAYS",
    days: "Friday",
    time: "11 PM - 4 AM",
    venue: "Papa Club",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/06/KingPapaDubai-EventPic.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    eventName: "SKY DANCE FRIDAYS",
    days: "Friday",
    time: "11:00 PM - 4 AM",
    venue: "OPAL ROOM",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/07/OPAL-ROOM-DUBAI-3.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    eventName: "URBAN PROJECT MONDAYS",
    days: "Monday",
    time: "11 PM - 4 AM",
    venue: "THE AVENUE CLUB",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/The-Rumba-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    eventName: "SHE’S WITH US SATURDAYS",
    days: "Saturday",
    time: "7 PM - 3 AM",
    venue: "Ce La Vi Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/She-is-with-us-event.jpg?fit=700%2C337&ssl=1",
  },
  {
    eventName: "SUMMER REUNION FRIDAYS",
    days: "Friday",
    time: "10 PM - 3 AM",
    venue: "Surf Club (indoor)",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/07/SummerReunion.jpg?fit=1170%2C2080&ssl=1",
  },
  {
    eventName: "ARYANA THURSDAYS",
    days: "Thursday",
    time: "11 PM - 4 AM",
    venue: "3bk Burj Khalifa",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Aryana-night-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    eventName: "CODE BLACK THURSDAYS",
    days: "Thursday",
    time: "11 PM - 4 AM",
    venue: "Papa Club",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/02/papa-club-dubai-best-party-thursdays-in-dubai.png?fit=1080%2C1573&ssl=1",
  },
  {
    eventName: "BAD HABITS WEDNESDAYS",
    days: "Wednesday",
    time: "11 PM - 4 AM",
    venue: "THE AVENUE CLUB",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Shutdown-shutdown-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    eventName: "URBAN DIARIES TUESDAYS",
    days: "Tuesday",
    time: "11 PM - 4 AM",
    venue: "Ora Club",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/06/Urban-Diaries-Party-Event-in-Dubai.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    eventName: "MONROE NIGHT SUNDAYS",
    days: "Sunday",
    time: "11 PM - 4 AM",
    venue: "Ora Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Monroe-Nights-Event.jpg?fit=700%2C338&ssl=1",
  },
];
