  // ✅ Restaurant Data added here
  export const restaurantData = [
    {
      id: 1,
      name: "Bluewater Restaurant",
      city: "Miami",
      state: "Florida",
      rating: 4,
      img: "https://images.unsplash.com/photo-1551782450-17144efb9c50?auto=format&w=800&q=60",
      desc: "Enjoy exquisite seafood and tropical vibes at the famous Bluewater Restaurant, right by Miami beach.",
    },
    {
      id: 2,
      name: "Skyline Lounge",
      city: "New York",
      state: "New York",
      rating: 5,
      img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&w=800&q=60",
      desc: "Luxury meets comfort at the Skyline Lounge — dine with breathtaking views of New York’s skyline.",
    },
    {
      id: 3,
      name: "Wave Night Club",
      city: "Los Angeles",
      state: "California",
      rating: 4,
      img: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=60",
      desc: "A perfect blend of dining and nightlife, Wave Night Club offers a modern twist on coastal cuisine.",
    },
    {
      id: 4,
      name: "Seaside Grill",
      city: "Miami",
      state: "Florida",
      rating: 3,
      img: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&w=800&q=60",
      desc: "Relax by the shore with mouthwatering grilled specials and live music every weekend.",
    },
    {
      id: 5,
      name: "Sunset Diner",
      city: "Los Angeles",
      state: "California",
      rating: 5,
      img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&w=800&q=60",
      desc: "Classic diner vibes with a gourmet twist — famous for its handmade burgers and cocktails.",
    },
    {
      id: 6,
      name: "Ocean Breeze Café",
      city: "Miami",
      state: "Florida",
      rating: 4,
      img: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&w=800&q=60",
      desc: "Chill atmosphere with freshly brewed coffee, ocean views, and live acoustic sessions.",
    },
    {
      id: 7,
      name: "City Lights Bistro",
      city: "New York",
      state: "New York",
      rating: 3,
      img: "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&w=800&q=60",
      desc: "Trendy bistro known for innovative cocktails and a cozy ambiance in downtown NYC.",
    },
    {
      id: 8,
      name: "Harbor View Grill",
      city: "San Francisco",
      state: "California",
      rating: 4,
      img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&w=800&q=60",
      desc: "A seafood lover’s paradise offering a beautiful view of the harbor and fresh daily catches.",
    },
    {
      id: 9,
      name: "Palm Grove Eatery",
      city: "Orlando",
      state: "Florida",
      rating: 5,
      img: "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&w=800&q=60",
      desc: "A tropical-themed eatery offering fresh fruit platters and exotic beverages under palm trees.",
    },
    {
      id: 10,
      name: "Golden Leaf Dine",
      city: "Chicago",
      state: "Illinois",
      rating: 4,
      img: "https://images.unsplash.com/photo-1551782450-17144efb9c50?auto=format&w=800&q=60",
      desc: "Elegant restaurant serving a fusion of Asian and Western cuisines with style.",
    },
    {
      id: 11,
      name: "Rooftop Bar & Grill",
      city: "Austin",
      state: "Texas",
      rating: 5,
      img: "https://images.unsplash.com/photo-1520201163981-8cc95007dd2a?auto=format&w=800&q=60",
      desc: "Dine under the stars with the city skyline at Austin’s most popular rooftop venue.",
    },
    {
      id: 12,
      name: "Moonlight Café",
      city: "Seattle",
      state: "Washington",
      rating: 4,
      img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=60",
      desc: "A peaceful café famous for its pastries, warm drinks, and calm moonlit view.",
    },
  ];