 export const venuesData = [
  {
    id: 1,
    name: "DREAM DINNER SHOW WED TO SUN",
    day: "Wed-Sun",
    time: "8 PM - 3 AM",
    venue: "Dream Restaurant",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Dream-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    id: 2,
    name: "KING PAPA FRIDAYS",
    day: "Friday",
    time: "11 PM - 4 AM",
    venue: "Papa Club",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/06/KingPapaDubai-EventPic.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    id: 3,
    name: "SKY DANCE FRIDAYS",
    day: "Friday",
    time: "11 PM - 4 AM",
    venue: "OPAL ROOM",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/07/OPAL-ROOM-DUBAI-3.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    id: 4,
    name: "URBAN PROJECT MONDAYS",
    day: "Monday",
    time: "11 PM - 4 AM",
    venue: "THE AVENUE CLUB",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/The-Rumba-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    id: 5,
    name: "SCANDALOUS THURSDAYS",
    day: "Thursday",
    time: "7 PM - 3 AM",
    venue: "Bagatelle Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/07/SCANDALOUS.jpg?fit=1080%2C1920&ssl=1",
  },
  {
    id: 6,
    name: "SHE’S WITH US SATURDAYS",
    day: "Saturday",
    time: "7 PM - 3 AM",
    venue: "Ce La Vi Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/She-is-with-us-event.jpg?fit=700%2C337&ssl=1",
  },
  {
    id: 7,
    name: "BORA BORA FRIDAYS",
    day: "Friday",
    time: "12 PM - 8 PM",
    venue: "KAIMANA BEACH",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/06/BORA-BORA-POOL-PARTY-IN-DUBAI-1.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    id: 8,
    name: "SUMMER REUNION FRIDAYS",
    day: "Friday",
    time: "10 PM - 3 AM",
    venue: "Surf Club (indoor)",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/07/SummerReunion.jpg?fit=1170%2C2080&ssl=1",
  },
  {
    id: 9,
    name: "ARYANA THURSDAYS",
    day: "Thursday",
    time: "11 PM - 4 AM",
    venue: "3bk Burj Khalifa",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Aryana-night-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    id: 10,
    name: "CODE BLACK THURSDAYS",
    day: "Thursday",
    time: "11 PM - 4 AM",
    venue: "Papa Club",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/02/papa-club-dubai-best-party-thursdays-in-dubai.png?fit=1080%2C1573&ssl=1",
  },
  {
    id: 11,
    name: "BAD HABITS WEDNESDAYS",
    day: "Wednesday",
    time: "11 PM - 4 AM",
    venue: "THE AVENUE CLUB",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Shutdown-shutdown-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    id: 12,
    name: "DIVA LADIES DAY WEDNESDAYS",
    day: "Wednesday",
    time: "1 PM - 9 PM",
    venue: "Playa Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Diva-ladied-day-event.jpg?fit=700%2C337&ssl=1",
  },
  {
    id: 13,
    name: "URBAN DIARIES TUESDAYS",
    day: "Tuesday",
    time: "11 PM - 4 AM",
    venue: "Ora Club",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/06/Urban-Diaries-Party-Event-in-Dubai.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    id: 14,
    name: "MONROE NIGHT SUNDAYS",
    day: "Sunday",
    time: "11 PM - 4 AM",
    venue: "Ora Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Monroe-Nights-Event.jpg?fit=700%2C338&ssl=1",
  },
  {
    id: 15,
    name: "Pool Side Day Brunch",
    day: "Sunday",
    time: "1 PM - 7 PM",
    venue: "Wany By Somiya",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2024/11/Pool-Trive-Event.jpg?fit=700%2C337&ssl=1",
  },
  {
    id: 16,
    name: "PINKY LADIES DAY WEDNESDAYS",
    day: "Wednesday",
    time: "12 PM - 10 PM",
    venue: "ALTO 54",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/05/Alto-54-Rooftop-Address-Sky-View-Downtown-Dubai-5.jpg?fit=1080%2C1350&ssl=1",
  },
  {
    id: 17,
    name: "ON111 THURSDAYS (BACK END OF SEPTEMBER)",
    day: "Thursday",
    time: "12 PM - 8 PM",
    venue: "O Beach Dubai",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/02/O-Beach-1.jpg?fit=1000%2C700&ssl=1",
  },
  {
    id: 18,
    name: "Lady in Red",
    day: "Wednesday",
    time: "7 PM - 1:30 AM",
    venue: "Raspoutine Restaurant",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/06/Raspoutine-Dubai-%D8%B1%D8%B3%D8%AA%D9%88%D8%B1%D8%A7%D9%86-%D8%B1%D8%B3%D9%BE%D9%88%D8%AA%DB%8C%D9%86-%D8%AF%D8%A8%DB%8C-16.jpg?fit=1080%2C1080&ssl=1",
  },
  {
    id: 19,
    name: "BAOLI CIRCLE TUESDAYS",
    day: "Tuesday",
    time: "7 PM - 3 AM",
    venue: "Baoli Restaurant",
    image: "https://i0.wp.com/thepartyfinder.com/wp-content/uploads/2025/05/Baoli-Circle-Baoli-Dubai-5.jpg?fit=1080%2C1333&ssl=1",
  },
];
